### ISSUE TITLE
[1.20.1 Forge] Locate structure does not autocomplete

### ISSUE THREAD

**Issue by MrKashew** [endorh/smart-completion#1]
![image](https://github.com/endorh/smart-completion/assets/53996665/d162a67d-aacb-430a-8036-2867ec4e6791)
however locate biome does
![image](https://github.com/endorh/smart-completion/assets/53996665/5bccfb04-6a86-43a2-9c75-2b4a4e255569)
[debug.log](https://github.com/endorh/smart-completion/files/12775948/debug.log)
[latest.log](https://github.com/endorh/smart-completion/files/12775949/latest.log)

**Comment by endorh** [comment]
Oh wow, that's surprising.

Seems like either the `locate structure` command is doing something weird or my mod is crashing/failing silently while sorting the suggestions.

I'll investigate it later, thanks for the report ^^

**Comment by endorh** [comment]
Alright, the difference between `/locate biome` and `/locate structure` was that the suggestions for `/locate biome` were being cached in the client, while those for `/locate structure` were being actually requested to the server (even in singleplayer).
The vanilla handling for those requests was discarding all except the last one, so my way of sending two of them at the same time caused one of them to be discarded, and the completions to wait forever.

I've fixed it in the latest version (1.1.0), which should be already available on CurseForge.
If you have the time, please confirm that the fix works for you.

**Comment by MrKashew** [comment]
verified fixed! thanks so much!
