### ISSUE TITLE
Breaks coordinate completion

### ISSUE THREAD

**Issue by ChiefArug** [endorh/smart-completion#2]
**Describe the bug**
Pressing tab to autofill coordinates of the block you are looking at fills in the wrong coordinates

**To Reproduce**
1. Look at a block
2. Type `/data get block`
3. Press tab three times to fill coordinates.
4. Notice the first two coords get filled correctly then the third one breaks it.

**Expected behavior**
The coordinates to fill correctly

**Screenshots**
https://github.com/endorh/smart-completion/assets/73862885/2566b172-964e-44c8-8bd6-f0ca26ed41c9 (video that doesnt seem to want to embed properly. also sorry about the orientation)

**Additional context**
It appears to be an issue with how it sorts the coords.
Im on 1.19.2 forge

**Comment by endorh** [comment]
Never checked that, thanks for reporting it!

I'm a bit bussy rn, but I'll look into a satisfying way to solve it as soon as I can.

**Comment by endorh** [comment]
I've just released a new (major) version that fixes this on 1.20.3+.

Once I have the time, I may try to backport at least the fixes of this update to earlier versions.

**Comment by endorh** [comment]
Hi, I've just backported the `2.0.1` version for earlier Minecraft versions, including `1.19.2`.
It should be already available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/smart-completion).

I'm closing the issue now, but feel free to reopen or comment if you're still having any related issues ^^
