### ISSUE TITLE
[1.21] Crash when trying to complete a player's name by pressing the tab key when the chat box is blank

### ISSUE THREAD

**Issue by PTALTS-LK** [endorh/smart-completion#4]
**Describe the bug**
Crash when trying to complete a player's name by pressing the tab key when the chat box is blank

**To Reproduce**
1. install minecraft 1.21 and fabric 0.16 and sc 2.0
2. Enter a world (multiplayer or singleplayer)
3. Open the chat box and press Tab to complete the player's name

**Expected behavior**
Player name completion pops up normally

**Screenshots**
none

**Additional context**
At first I thought it was an issue with the Emojiful mod, but after my testing, the issue was on sc, but I had already filed an issue on Emojiful and the log was on that issue
https://github.com/InnovativeOnlineIndustries/Emojiful/issues/116

**Comment by endorh** [comment]
Hi, thanks for reporting the issue, and sorry for the trouble.

I'll try to get a fix out asap.

**Comment by endorh** [comment]
I've just released a new version ([`2.0.1`](https://www.curseforge.com/minecraft/mc-mods/smart-completion/files/5633626)), which should solve the crash.

If you have the time, please verify that it works for you, specially with the Emojiful mod ^^

**Comment by PTALTS-LK** [comment]
> I've just released a new version ([`2.0.1`](https://www.curseforge.com/minecraft/mc-mods/smart-completion/files/5633626)), which should solve the crash.
> 
> If you have the time, please verify that it works for you, specially with the Emojiful mod ^^

It worked 👍
