### ISSUE TITLE
[1.21][sc 2.0.1] Crash when using completion in command blocks

### ISSUE THREAD

**Issue by PTALTS-LK** [endorh/smart-completion#5]
**Describe the bug**
When I try to complete a command in the command block, the game crashes when scrolling through the completion menu in "@e[***]".

**To Reproduce**
1. install minecraft 1.21 and fabric 0.16 and sc 2.0.1
2. Enter a world (multiplayer or singleplayer)
3. Place a command block and open the GUI type, type "/tp @e[", then roll the mouse wheel and move the mouse to each candidate

**Expected behavior**
Normal without crashing

**Screenshots**
None

**Additional context**

[crash-2024-08-18_22.15.34-client.txt](https://github.com/user-attachments/files/16649038/crash-2024-08-18_22.15.34-client.txt)
[latest.log](https://github.com/user-attachments/files/16649040/latest.log)

**Comment by endorh** [comment]
Hi, sorry for the delay, I somehow messed up my mail notifications and missed this until now.

I'll fix it asap. Thank you for reporting the crashes so promptly 😅

**Comment by endorh** [comment]
I just released the fix (`v2.0.2` on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/smart-completion/files/5666868)).

It was a silly mistake 😅, ignoring the maximum number of suggestions that should be rendered when not in the chat screen.
If you have the time to verify it works for you, feel free to close the issue ^^

**Comment by PTALTS-LK** [comment]
Problem solved, thank you for your passion for mod development👍
